### ISSUE TITLE
where to save my access token?

### ISSUE THREAD

**Issue by mayahartlieb** [sousa-andre/vscode-activity-github#1]
I would like to use the extension I have installed, but I don't know where to save the setting below with the access token :
{
    "activityGithub.auth.accessToken": "YOUR_TOKEN"
}

thank you in advance for your help 
Maya

**Comment by sousa-andre** [comment]
Click on View, choose Command Pallete, and search by ">Preferences: Open Settings (JSON)".
Add `"activityGithub.auth.accessToken": "YOUR_TOKEN"` on the root of the JSON object and save the file.
